version: '3'
services:
  crawler:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: python crawler.py
    environment:
      - MAX_DEPTH=${MAX_DEPTH:-5}
      - MAX_PAGES=${MAX_PAGES:-100}
  
  translator:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: python translate.py