name: Deploy Uniapp Crawler

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Fetch the repository content
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker environment for building images
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Authenticate with Docker Hub using repository secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Add the translation API key to the environment file
    - name: Add DEEPL_API_KEY to environment
      run: echo "DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }}" >> .env

    # Install Python dependencies required by the crawler and translator
    - name: Install Python dependencies
      run: |
        pip install -r app/requirements.txt

    # Ensure docker-compose is available for orchestrating containers
    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Build and run the crawler and translator in Docker
    - name: Build and run Docker image
      run: |
        docker-compose up --build

    # Copy translated files to the docs folder for GitHub Pages
    - name: Copy translated documents to docs folder
      run: |
        mkdir -p docs
        cp -r data/vi/* docs/
        ls -la docs/

    # Stop and remove Docker containers
    - name: Clean up
      run: |
        docker-compose down

    # Commit and push the generated docs to the repository
    - name: Commit updates to docs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Update docs with latest translations" || echo "No changes to commit"
        git push